FROM python:3.9.7

RUN mkdir /app
WORKDIR /app

RUN apt-get --allow-releaseinfo-change update
RUN apt-get install -y git gcc g++ libgl1

RUN /usr/local/bin/python -m pip install --upgrade pip
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest

ENTRYPOINT ["python", "-m", "pytest", "-s", "."]