FROM --platform=linux/amd64 python:3.8.16-slim

COPY pyproject.toml /app/pyproject.toml

RUN apt-get --allow-releaseinfo-change update && \
    apt-get install --no-install-recommends -y git gcc g++ libgl1 && \
    pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -e 'app/.[test]' && \
    apt-get purge git -y && apt-get autoremove -y && apt-get clean && rm -rf /root/.cache/pip/*

WORKDIR /app
ENTRYPOINT ["python3", "-m", "pytest", "-s", "."]