FROM python:3.9.7-slim

COPY requirements.txt /app/requirements.txt

RUN apt-get --allow-releaseinfo-change update && \
    apt-get install --no-install-recommends -y git gcc g++ libgl1 && \
    pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -r /app/requirements.txt && \
    pip3 install --no-cache-dir pytest && \
    apt-get purge git -y && apt-get autoremove -y && apt-get clean && rm -rf /root/.cache/pip/*

WORKDIR /app
ENTRYPOINT ["python3", "-m", "pytest", "-s", "."]