import os
from optinist.api.dir_path import DIRPATH
from optinist.api.utils.filepath_creater import join_filepath

configfile: join_filepath([DIRPATH.ROOT_DIR, 'config.yaml'])

for rule, details in config["rules"].items():
    include: details["rule_file"]

rule all:
    input: [join_filepath([DIRPATH.OUTPUT_DIR, x]) for x in config["last_output"]]