rule:
    input:
        config["rules"]["suite2p_roi"]["input"]
    output:
        config["rules"]["suite2p_roi"]["output"]
    conda:
        "../../envs/suite2p_env.yaml"
    script:
        "../../scripts/suite2p/suite2p_roi.py"
