rule:
    input:
        config["rules"]["suite2p_spike_deconv"]["input"]
    output:
        config["rules"]["suite2p_spike_deconv"]["output"]
    conda:
        "../../envs/suite2p_env.yaml"
    script:
        "../../scripts/suite2p/suite2p_spike_deconv.py"