FROM --platform=linux/amd64 python:3.8.16-slim

WORKDIR /app

RUN apt-get --allow-releaseinfo-change update && \
    apt-get install --no-install-recommends -y git gcc g++ libgl1 && \
    apt-get purge git -y && apt-get autoremove -y && apt-get clean

COPY pyproject.toml .
RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -e '.[test]'

ENTRYPOINT ["python3", "-m", "pytest", "-s", "."]
