last_output:
  - b9d1513e/caiman_cnmf/caiman_cnmf.pkl
rules:
  input_0:
    hdf5Path: null
    input:
      - test.tif
    nwbfile:
      device:
        description: Microscope Information
        manufacturer: Microscope Manufacture
        name: Microscope device
      experiment_description: None
      identifier: optinist
      image_series:
        starting_frame:
          - 0
        starting_time: 0
      imaging_plane:
        description: standard
        excitation_lambda: 600.0
        imaging_rate: 30.0
        indicator: GCaMap
        location: V1
        name: ImagingPlane
      ophys:
        plane_segmentation:
          description: ''
          name: PlaneSegmentation
      optical_channel:
        description: optical channel
        emission_lambda: 500.0
        name: OpticalChannel
      session_description: optinist
    output: b9d1513e/input_0/mouse2p_2_donotouse.pkl
    params: {}
    path: null
    return_arg: input_0
    type: image
  caiman_cnmf:
    hdf5Path: null
    input:
      - b9d1513e/caiman_mc/caiman_mc.pkl
    nwbfile: null
    output: b9d1513e/caiman_cnmf/caiman_cnmf.pkl
    params:
      K: 4
      gSig:
        - 4
        - 4
      merge_thr: 0.85
      method_init: greedy_roi
      nb: 2
      p: 1
      rf: null
      ssub: 1
      stride: 6
      thr: 0.9
      tsub: 1
    path: caiman/caiman_cnmf
    return_arg:
      mc_images: images
    type: caiman_cnmf
  caiman_mc:
    hdf5Path: null
    input:
      - b9d1513e/input_0/mouse2p_2_donotouse.pkl
    nwbfile: null
    output: b9d1513e/caiman_mc/caiman_mc.pkl
    params:
      border_nan: copy
      gSig_filt: null
      is3D: false
      max_deviation_rigid: 3
      max_shifts:
        - 6
        - 6
      min_mov: null
      niter_rig: 1
      nonneg_movie: true
      num_frames_split: 80
      num_splits_to_process_els: null
      num_splits_to_process_rig: null
      overlaps:
        - 32
        - 32
      pw_rigid: false
      shifts_opencv: true
      splits_els: 14
      splits_rig: 14
      strides:
        - 96
        - 96
      upsample_factor_grid: 4
      use_cuda: false
    path: caiman/caiman_mc
    return_arg:
      input_0: image
    type: caiman_mc
