last_output:
  - fd536a4f/suite2p_spike_deconv/suite2p_spike_deconv.pkl
rules:
  input_0:
    hdf5Path: null
    input:
      - test.tif
    nwbfile:
      device:
        description: Microscope Information
        manufacturer: Microscope Manufacture
        name: Microscope device
      experiment_description: None
      identifier: optinist
      image_series:
        starting_frame:
          - 0
        starting_time: 0
      imaging_plane:
        description: standard
        excitation_lambda: 600.0
        imaging_rate: 30.0
        indicator: GCaMap
        location: V1
        name: ImagingPlane
      ophys:
        plane_segmentation:
          description: ''
          name: PlaneSegmentation
      optical_channel:
        description: optical channel
        emission_lambda: 500.0
        name: OpticalChannel
      session_description: optinist
    output: fd536a4f/input_0/test.pkl
    params: {}
    path: null
    return_arg: input_0
    type: image
  suite2p_file_convert:
    hdf5Path: null
    input:
      - fd536a4f/input_0/test.pkl
    nwbfile: null
    output: fd536a4f/suite2p_file_convert/suite2p_file_convert.pkl
    params:
      batch_size: 500
      do_registration: 1
      force_sktiff: false
      nchannels: 1
      nplanes: 1
    path: suite2p/suite2p_file_convert
    return_arg:
      input_0: image
    type: suite2p_file_convert
  suite2p_registration:
    hdf5Path: null
    input:
      - fd536a4f/suite2p_file_convert/suite2p_file_convert.pkl
    nwbfile: null
    output: fd536a4f/suite2p_registration/suite2p_registration.pkl
    params:
      1Preg: false
      align_by_chan: 1
      bidi_corrected: false
      bidiphase: 0
      block_size:
        - 128
        - 128
      diameter: 0
      do_bidiphase: false
      frames_include: -1
      functional_chan: 1
      keep_movie_raw: false
      maxregshift: 0.1
      maxregshiftNR: 5
      nonrigid: true
      pre_smooth: 0
      reg_tif: false
      smooth_sigma: 1.15
      smooth_sigma_time: 0
      snr_thresh: 1.2
      spatial_hp_reg: 42
      spatial_taper: 40
      th_badframes: 1
    path: suite2p/suite2p_registration
    return_arg:
      ops: ops
    type: suite2p_registration
  suite2p_roi:
    hdf5Path: null
    input:
      - fd536a4f/suite2p_registration/suite2p_registration.pkl
    nwbfile: null
    output: fd536a4f/suite2p_roi/suite2p_roi.pkl
    params:
      allow_overlap: false
      fs: 10
      high_pass: 100
      inner_neuropil_radius: 2
      max_iterations: 20
      max_overlap: 0.75
      min_neuropil_pixels: 350
      nbinned: 5000
      neucoeff: 0.7
      preclassify: 0
      soma_crop: true
      sparse_mode: true
      spatial_hp_detect: 25
      spatial_scale: 0
      tau: 1
      threshold_scaling: 1
    path: suite2p/suite2p_roi
    return_arg:
      ops: ops
    type: suite2p_roi
  suite2p_spike_deconv:
    hdf5Path: null
    input:
      - fd536a4f/suite2p_roi/suite2p_roi.pkl
    nwbfile: null
    output: fd536a4f/suite2p_spike_deconv/suite2p_spike_deconv.pkl
    params:
      baseline: maximin
      neucoeff: 0.7
      prctile_baseline: 8
      sig_baseline: 10
      win_baseline: 60
    path: suite2p/suite2p_spike_deconv
    return_arg:
      ops: ops
    type: suite2p_spike_deconv
