last_output:
- 132545b3/suite2p_roi_w8unnq1iai/suite2p_roi.pkl
rules:
  input_0:
    hdf5Path: null
    input:
    - test.tif
    nwbfile:
      device:
        description: Microscope Information
        manufacturer: Microscope Manufacture
        name: Microscope device
      experiment_description: None
      identifier: optinist
      image_series:
        starting_frame:
        - 0
        starting_time: 0
      imaging_plane:
        description: standard
        excitation_lambda: 600
        imaging_rate: 30
        indicator: GCaMap
        location: V1
        name: ImagingPlane
      ophys:
        plane_segmentation:
          description: ''
          name: PlaneSegmentation
      optical_channel:
        description: optical channel
        emission_lambda: 500
        name: OpticalChannel
      session_description: optinist
    output: 132545b3/input_0/test.pkl
    params: {}
    path: null
    return_arg: input_0
    type: image
  suite2p_file_convert_9btk4euow9:
    hdf5Path: null
    input:
    - 132545b3/input_0/test.pkl
    nwbfile: null
    output: 132545b3/suite2p_file_convert_9btk4euow9/suite2p_file_convert.pkl
    params:
      batch_size: 500
      do_registration: 1
      force_sktiff: false
      nchannels: 1
      nplanes: 1
    path: suite2p/suite2p_file_convert
    return_arg:
      input_0: image
    type: suite2p_file_convert
  suite2p_roi_w8unnq1iai:
    hdf5Path: null
    input:
    - 132545b3/suite2p_file_convert_9btk4euow9/suite2p_file_convert.pkl
    nwbfile: null
    output: 132545b3/suite2p_roi_w8unnq1iai/suite2p_roi.pkl
    params:
      allow_overlap: false
      fs: 10
      high_pass: 100
      inner_neuropil_radius: 2
      max_iterations: 20
      max_overlap: 0.75
      min_neuropil_pixels: 350
      nbinned: 5000
      neucoeff: 0.7
      preclassify: 0
      soma_crop: true
      sparse_mode: true
      spatial_hp_detect: 25
      spatial_scale: 0
      tau: 1
      threshold_scaling: 1
    path: suite2p/suite2p_roi
    return_arg:
      ops: ops
    type: suite2p_roi
