rule:
    input:
        config["rules"]["cross_correlation"]["input"]
    output:
        config["rules"]["cross_correlation"]["output"]
    conda:
        "../../../envs/optinist_env.yaml"
    script:
        "../../../scripts/optinist/neural_population_analysis/cross_correlation.py"