# deconvolution settings
baseline: 'maximin'  # baselining mode (can also choose 'prctile')
win_baseline: 60.     # window for maximin
sig_baseline: 10.     # smoothing constant for gaussian filter
prctile_baseline: 8.  # optional (whether to use a percentile baseline)
neucoeff: .7          # neuropil coefficient